version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: .
    links:
     - db
    ports:
     - 8081:8081
    volumes:
     - ~/Development/go/demo/src:/go/src/github.com/user/app
     - ~/Development/go/demo/configs:/etc/myapi/
    restart: always